### ISSUE TITLE
某些情况下，用leakCanary会报内存泄漏

### ISSUE THREAD

**Issue by kw13630** [SheHuan/NiceDialog#22]
HandlerThread.<Java Local>
Message.obj(excluded)
NiceDialog

**Comment by JohnsonJLi** [comment]
我这里是一直报内存泄漏

**Comment by gogolq** [comment]
有人解决这个问题了吗

**Comment by XuQK** [comment]
同样，每次使用都报

**Comment by JohnsonJLi** [comment]
@Override
    protected void onDestroy() {
        if (null != dialogFragment) {
            dialogFragment.dismiss();
            dialogFragment = null;
        }
        super.onDestroy();
    }
使用完关闭 赋null

**Comment by JohnsonJLi** [comment]
我是这样解决的

**Comment by XuQK** [comment]
@JohnsonJLi 我是直接用的新建的匿名类，没有引用这个dialog对象

**Comment by JohnsonJLi** [comment]
@XuQK  你可以去leakCanary 的 Issue里面看下 
还有  我把 fragments 注释掉了  
//     Optional, if you use support library fragments:
//    debugImplementation 'com.squareup.leakcanary:leakcanary-support-fragment:1.6.2'

**Comment by fansonq** [comment]
> 同样，每次使用都报

请问你解决内存泄漏问题了嘛？求指教

**Comment by fansonq** [comment]
> HandlerThread.
> Message.obj(excluded)
> NiceDialog

请问你解决内存泄漏问题了嘛？求指教

**Comment by fansonq** [comment]
> 我这里是一直报内存泄漏

请问你解决内存泄漏问题了嘛？求指教

**Comment by hhecoder** [comment]
同问题，所以是真的内存泄漏还是误报？
